insert into db_car_test.car (make,model,car_type,seats,
				fuel_usage,gearbox) values 
('Acura','RDX','SUV',5,11.7,'AUTOMATIC'),
('Alfa Romeo','Stelvio','SUV',5,10.6,'AUTOMATIC'),
('Audi','Q3','SUV',5,11.7,'AUTOMATIC'),
('Mercedes-Benz','G-Class','SUV',5,21.3,'AUTOMATIC'),
('Jeep','Grand Cherokee','SUV',5,15.6,'AUTOMATIC'),
('Toyota','Sequoia','SUV',7,18,'AUTOMATIC'),
('Lexus','GX','SUV',7,15.6,'AUTOMATIC'),
('Jeep','Wrangler','SUV',5,13.8,'MANUAL'),
('Subaru','Forester','SUV',5,9.8,'MANUAL'),
('Mitsubishi','Outlander Sport','SUV',5,13.8,'MANUAL'),

('Nissan','Frontier','TRUCK',5,13.8,'MANUAL'),
('Toyota','Tacoma','TRUCK',5,13.8,'MANUAL'),
('Chevrolet','Colorado','TRUCK',5,11.7,'AUTOMATIC'),
('Chevrolet','Silverado','TRUCK',6,14.7,'AUTOMATIC'),

('Honda','Odyssey','VAN',8,12.3,'AUTOMATIC'),
('Kia','Sedona','VAN',8,12.8,'AUTOMATIC'),
('Toyota','Sienna','VAN',8,12.3,'AUTOMATIC'),
('Chrysler','Pacifica','VAN',6,13.8,'AUTOMATIC'),
('Chrysler','Pacifica Hybrid','VAN',6,13.8,'AUTOMATIC'),
('Dodge','Grand Caravan','VAN',6,13.8,'AUTOMATIC'),

('Audi','A5','CONVERTIBLE',4,14.2,'MANUAL'),
('BMW','2-Series','CONVERTIBLE',4,13.8,'MANUAL'),
('BMW','6-Series','CONVERTIBLE',4,13.8,'MANUAL'),
('Audi','A3','CONVERTIBLE',4,12.8,'AUTOMATIC'),
('Audi','A5','CONVERTIBLE',4,14.8,'AUTOMATIC'),

('Volkswagen','Golf SportWagen 2017','WAGON',5,15.8,'MANUAL'),
('Volkswagen','Golf SportWagen 2018','WAGON',5,15.8,'MANUAL'),
('Audi','Allroad','WAGON',5,15,'AUTOMATIC'),
('Fiat','500L','WAGON',5,15.8,'AUTOMATIC'),

('Dodge','Challanger','SPORT',5,12.6,'AUTOMATIC'),
('Chevrolet','Camaro','SPORT',4,14.6,'MANUAL'),
('Ford','Mustang','SPORT',4,13.2,'MANUAL'),
('Acura','NSX','SPORT',4,12.3,'AUTOMATIC'),
('Alfa Romeo','4C','SPORT',4,15.4,'AUTOMATIC'),

('Audi','A4','LUXURY',5,12.4,'MANUAL'),
('BMW','3-Series','LUXURY',5,13.1,'MANUAL'),
('Audi','A5','LUXURY',5,11.4,'AUTOMATIC'),
('Audi','A6','LUXURY',5,11.2,'AUTOMATIC'),
('Audi','TT','LUXURY',2,11.9,'AUTOMATIC'),
('Audi','R8','LUXURY',2,10.2,'AUTOMATIC'),
 
('Audi','A5','SEDAN',5,10.2,'MANUAL'),
('BMW','3-Series','SEDAN',5,9.2,'MANUAL'),
('Cadillac','ATS','SEDAN',5,12.3,'MANUAL'),
('Chevrolet','Cruze','SEDAN',5,8.7,'MANUAL'),
('Acura','ILX','SEDAN',5,8.7,'AUTOMATIC'),
('Alfa Romeo','Giulia','SEDAN',5,9.7,'AUTOMATIC'),
('Ford','Fiesta','SEDAN',5,9.5,'AUTOMATIC'),
('Ford','Focus','SEDAN',5,10.1,'AUTOMATIC'),
('Honda','Civic','SEDAN',5,7.9,'AUTOMATIC'),
('Hyundai','Accent','SEDAN',5,12.7,'AUTOMATIC'),
('Kia','Forte','SEDAN',5,11.7,'AUTOMATIC'),
('Kia','Rio','SEDAN',5,11.4,'AUTOMATIC'),
('Mazda','Mazda3','SEDAN',5,13.1,'AUTOMATIC'),
('Mercedes-Benz','CLA-Class','SEDAN',5,10,'AUTOMATIC');