insert into db_car_test.car (make,model,car_type,seats,
				fuel_usage,gearbox) values 
('Acura','RDX','SUV',5,11.7,'Automatic'),
('Alfa Romeo','Stelvio','SUV',5,10.6,'Automatic'),
('Audi','Q3','SUV',5,11.7,'Automatic'),
('Mercedes-Benz','G-Class','SUV',5,21.3,'Automatic'),
('Jeep','Grand Cherokee','SUV',5,15.6,'Automatic'),
('Toyota','Sequoia','SUV',7,18,'Automatic'),
('Lexus','GX','SUV',7,15.6,'Automatic'),
('Jeep','Wrangler','SUV',5,13.8,'Manual'),
('Subaru','Forester','SUV',5,9.8,'Manual'),
('Mitsubishi','Outlander Sport','SUV',5,13.8,'Manual'),

('Nissan','Frontier','Truck',5,13.8,'Manual'),
('Toyota','Tacoma','Truck',5,13.8,'Manual'),
('Chevrolet','Colorado','Truck',5,11.7,'Automatic'),
('Chevrolet','Silverado','Truck',6,14.7,'Automatic'),

('Honda','Odyssey','Van',8,12.3,'Automatic'),
('Kia','Sedona','Van',8,12.8,'Automatic'),
('Toyota','Sienna','Van',8,12.3,'Automatic'),
('Chrysler','Pacifica','Van',6,13.8,'Automatic'),
('Chrysler','Pacifica Hybrid','Van',6,13.8,'Automatic'),
('Dodge','Grand Caravan','Van',6,13.8,'Automatic'),

('Audi','A5','Convertible',4,14.2,'Manual'),
('BMW','2-Series','Convertible',4,13.8,'Manual'),
('BMW','6-Series','Convertible',4,13.8,'Manual'),
('Audi','A3','Convertible',4,12.8,'Automatic'),
('Audi','A5','Convertible',4,14.8,'Automatic'),

('Volkswagen','Golf SportWagen 2017','Wagon',5,15.8,'Manual'),
('Volkswagen','Golf SportWagen 2018','Wagon',5,15.8,'Manual'),
('Audi','Allroad','Wagon',5,15,'Automatic'),
('Fiat','500L','Wagon',5,15.8,'Automatic'),

('Dodge','Challanger','Sport',5,12.6,'Automatic'),
('Chevrolet','Camaro','Sport',4,14.6,'Manual'),
('Ford','Mustang','Sport',4,13.2,'Manual'),
('Acura','NSX','Sport',4,12.3,'Automatic'),
('Alfa Romeo','4C','Sport',4,15.4,'Automatic'),

('Audi','A4','Luxury',5,12.4,'Manual'),
('BMW','3-Series','Luxury',5,13.1,'Manual'),
('Audi','A5','Luxury',5,11.4,'Automatic'),
('Audi','A6','Luxury',5,11.2,'Automatic'),
('Audi','TT','Luxury',2,11.9,'Automatic'),
('Audi','R8','Luxury',2,10.2,'Automatic'),
 
('Audi','A5','Sedan',5,10.2,'Manual'),
('BMW','3-Series','Sedan',5,9.2,'Manual'),
('Cadillac','ATS','Sedan',5,12.3,'Manual'),
('Chevrolet','Cruze','Sedan',5,8.7,'Manual'),
('Acura','ILX','Sedan',5,8.7,'Automatic'),
('Alfa Romeo','Giulia','Sedan',5,9.7,'Automatic'),
('Ford','Fiesta','Sedan',5,9.5,'Automatic'),
('Ford','Focus','Sedan',5,10.1,'Automatic'),
('Honda','Civic','Sedan',5,7.9,'Automatic'),
('Hyundai','Accent','Sedan',5,12.7,'Automatic'),
('Kia','Forte','Sedan',5,11.7,'Automatic'),
('Kia','Rio','Sedan',5,11.4,'Automatic'),
('Mazda','Mazda3','Sedan',5,13.1,'Automatic'),
('Mercedes-Benz','CLA-Class','Sedan',5,10,'Automatic');